language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm

matrix:
    allow_failures:
        - php: hhvm

script:
  # Validate composer.json file.
  - composer validate
  # Try to install all requirements.
  - composer install
  # Check if there is a security issue with the required packages.
  # Skipping this check for HHVM, till this is merged: https://github.com/facebook/hhvm/issues/1859
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then bin/security-checker security:check composer.lock; fi;'

notifications:
  email:
    - php@h4cc.de
